### ISSUE TITLE
Nimble 9.0 has breaking changes

### ISSUE THREAD

**Issue by aelkady** [leandromperez/specleaks#19]
There is a [release candidate](https://github.com/Quick/Nimble/releases/tag/v9.0.0-rc.3) for version 9 of Nimble available that has support for XCode 12 (more info [here](https://github.com/Quick/Nimble/issues/809)). However, updating to Nimble 9 breaks this Pod.

I have attached a screenshot that indicates specifically which file/part of the code is causing the compilation issues, it is just a type mismatch between `TimeInterval` and `DispatchTimeInterval` in `Expectation+Leaks.swift`.
![Screen Shot 2020-09-23 at 11 17 42 AM](https://user-images.githubusercontent.com/6837609/94033558-156f7c80-fd8f-11ea-894c-8cdef951a2c3.png)

**Comment by fkalai** [comment]
Hello guys, is this fix will be released soon?

**Comment by leandromperez** [comment]
Just merged it!
