### ISSUE TITLE
Use of unresolved identifier 'leak'

### ISSUE THREAD

**Issue by source-creator** [leandromperez/specleaks#3]
First of all, thank you for this library, I am excited to start using it.

It appears I am getting this error because `Matchers.swift` was only added after the first POD release.

Please could you deploy a new release?

**Comment by leandromperez** [comment]
Hi @source-creator I am so sorry for the late response. I couldn't make time to work on it until just now. Can you please take a look at it now? 0.1.1 should work if you use SpecLeaks in your test target.
