### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by igorkulman** [leandromperez/specleaks#5]
Any plans to add Carthage support?

**Comment by leandromperez** [comment]
@igorkulman I gave it a shot last night but I couldn't make it work. I'll try again soon but I'm quite busy these days

**Comment by josueruiz7** [comment]
Hi @leandromperez   any news about it?

thanks

**Comment by josueruiz7** [comment]
@leandromperez when it could be ready?

**Comment by leandromperez** [comment]
Thanks @josueruiz7 for adding support for Carthage!
 I've just created a test project and placed it inside the repo. I'm closing this issue
