### ISSUE TITLE
Conversion to Swift 5

### ISSUE THREAD

**Issue by fmirault** [leandromperez/specleaks#7]
Hi !

Thank you for this very cool library.
With Swift 5, there is a warning because the library was not build with Swift 5.
I think there are not so many changes since 4.2, so maybe a new version with swift version updated could be useful for every Swift 5 users :)

**Comment by leandromperez** [comment]
Hi @fmirault, thanks! 
I hope I can get to work a bit on this next week, but I'm very busy these days. You're more than welcome to open a PR if you want to and can help a little.
Thanks

**Comment by leandromperez** [comment]
Hi @fmirault I've just added support for Swift 5. If you have time to check it out, please let me know if it works for you. Thanks!

**Comment by fmirault** [comment]
It works perfectly ! Thank you ! :)
